CREATE TABLE IF NOT EXISTS "StreamingHistory" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"played_at" TIMESTAMP NOT NULL,
	"platform_used" VARCHAR(255),
	"connection_country" CHAR(2),
	"track_uri" VARCHAR(255),
	"artist_uri" VARCHAR(255),
	"album_uri" VARCHAR(255),
	"is_podcast" BOOLEAN NOT NULL,
	"play_start_reason" VARCHAR(255),
	"play_end_reason" VARCHAR(255),
	"shuffle_enabled" BOOLEAN,
	"skipped_track" BOOLEAN,
	"milliseconds_played" INTEGER,
	"offline_playback" BOOLEAN,
	"offline_timestamp" BIGINT,
	"incognito_mode" BOOLEAN,
	PRIMARY KEY("user_id", "played_at")
);




CREATE TABLE IF NOT EXISTS "LibraryTracks" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"track_uri" VARCHAR(255) NOT NULL,
	"artist_uri" VARCHAR(255),
	"album_uri" VARCHAR(255),
	"in_playlist" BOOLEAN,
	"liked" BOOLEAN,
	PRIMARY KEY("user_id", "track_uri")
);




CREATE TABLE IF NOT EXISTS "SoundCapsule" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"date" DATE NOT NULL,
	"streamCount" INTEGER,
	"secondsPlayed" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "SoundCapsule_TopTracks" (
	"soundcapsule_id" INTEGER NOT NULL,
	"track_uri" VARCHAR(255) NOT NULL,
	"streamCount" INTEGER,
	PRIMARY KEY("soundcapsule_id", "track_uri")
);




CREATE TABLE IF NOT EXISTS "SoundCapsule_TopArtists" (
	"soundcapsule_id" INTEGER NOT NULL,
	"artist_uri" VARCHAR(255) NOT NULL,
	"streamCount" INTEGER,
	PRIMARY KEY("soundcapsule_id", "artist_uri")
);




CREATE TABLE IF NOT EXISTS "SoundCapsule_TopGenres" (
	"soundcapsule_id" INTEGER NOT NULL,
	"genre_name" VARCHAR(255) NOT NULL,
	PRIMARY KEY("soundcapsule_id", "genre_name")
);




CREATE TABLE IF NOT EXISTS "SoundCapsule_TimeOfDayStats" (
	"soundcapsule_id" INTEGER NOT NULL,
	"period" VARCHAR(50) NOT NULL,
	"secondsPlayed" INTEGER,
	PRIMARY KEY("soundcapsule_id", "period")
);




CREATE TABLE IF NOT EXISTS "User" (
	"user_id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(255) NOT NULL,
	PRIMARY KEY("user_id")
);




CREATE TABLE IF NOT EXISTS "Tracks" (
	"uri" VARCHAR(255) NOT NULL UNIQUE,
	"track_name" VARCHAR(255),
	PRIMARY KEY("uri")
);




CREATE TABLE IF NOT EXISTS "Artist" (
	"uri" VARCHAR(255) NOT NULL UNIQUE,
	"artist_name" VARCHAR(255),
	PRIMARY KEY("uri")
);




CREATE TABLE IF NOT EXISTS "Album" (
	"uri" VARCHAR(255) NOT NULL UNIQUE,
	"album_name" VARCHAR(255),
	PRIMARY KEY("uri")
);



ALTER TABLE "StreamingHistory"
ADD FOREIGN KEY("track_uri") REFERENCES "Tracks"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "StreamingHistory"
ADD FOREIGN KEY("artist_uri") REFERENCES "Artist"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "StreamingHistory"
ADD FOREIGN KEY("album_uri") REFERENCES "Album"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "StreamingHistory"
ADD FOREIGN KEY("user_id") REFERENCES "User"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "SoundCapsule"
ADD FOREIGN KEY("user_id") REFERENCES "User"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "LibraryTracks"
ADD FOREIGN KEY("user_id") REFERENCES "User"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "SoundCapsule_TopTracks"
ADD FOREIGN KEY("soundcapsule_id") REFERENCES "SoundCapsule"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "SoundCapsule_TopArtists"
ADD FOREIGN KEY("soundcapsule_id") REFERENCES "SoundCapsule"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "SoundCapsule_TopGenres"
ADD FOREIGN KEY("soundcapsule_id") REFERENCES "SoundCapsule"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "SoundCapsule_TimeOfDayStats"
ADD FOREIGN KEY("soundcapsule_id") REFERENCES "SoundCapsule"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "LibraryTracks"
ADD FOREIGN KEY("track_uri") REFERENCES "Tracks"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "LibraryTracks"
ADD FOREIGN KEY("track_uri") REFERENCES "Artist"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "LibraryTracks"
ADD FOREIGN KEY("track_uri") REFERENCES "Album"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "SoundCapsule_TopTracks"
ADD FOREIGN KEY("track_uri") REFERENCES "Tracks"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "SoundCapsule_TopArtists"
ADD FOREIGN KEY("artist_uri") REFERENCES "Artist"("uri")
ON UPDATE NO ACTION ON DELETE NO ACTION;